######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 20 20:30:18 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MachineLearningApp.h
FORMS += MachineLearningApp.ui
SOURCES += MachineLearningApp.cpp main.cpp
