<<<<<<< HEAD
######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 20 20:30:18 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MachineLearningApp.h
FORMS += MachineLearningApp.ui
SOURCES += MachineLearningApp.cpp main.cpp
=======
#-------------------------------------------------
#
# Project created by QtCreator 2016-11-15T22:10:31
#
#-------------------------------------------------

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = MachineLearningApp
TEMPLATE = app


SOURCES += main.cpp\
    MachineLearningApp.cpp \
    data2plot.cpp

HEADERS  += \
    MachineLearningApp.h \
    data2plot.h

FORMS    += \
    MachineLearningApp.ui
>>>>>>> 6083e925f52f3867b3968e2a4d4f88830e65e212
