######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 20 20:39:33 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += data2plot.h MachineLearningApp.h
FORMS += MachineLearningApp.ui
SOURCES += MachineLearningApp.cpp main.cpp
